CREATE TABLE IF NOT EXISTS payments (
    id VARCHAR(64) PRIMARY KEY,
    order_id VARCHAR(64) NOT NULL UNIQUE,
    transaction_id VARCHAR(64) NOT NULL DEFAULT '',
    amount BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL
);
